rootUrl: https://redveronika.github.io/ya-mm-task
gridUrl: http://ondemand.saucelabs.com/wd/hub
calibrate: false
screenshotsDir: ./app/tests/gemini/screens

browsers:
  chrome-latest:
    desiredCapabilities:
      browserName: chrome
      platform: WINDOWS

system:
  projectRoot: ./
  sourceRoot: ./app
  exclude: ["*node_modules*", "*webpack*", "*app/assets*", "*app/blocks*", "*app/reducers*", "*app/utils*"]
  plugins:
    sauce:
      username: proccess.env.SAUCE_USERNAME
      accessKey: proccess.env.SAUCE_ACCESS_KEY

sets:
  chrome:
    files:
    - ./app/tests/gemini
    browsers:
    - chrome-latest
