rootUrl: http://localhost:8080/main
calibrate: false
screenshotsDir: './app/tests/gemini/screens'

browsers:
  chrome-latest:
    screenshotsDir: './chrome-screens'
    desiredCapabilities:
      browserName: chrome
  firefox-latest:
    screenshotsDir: './ff-screens'
    desiredCapabilities:
      browserName: firefox
      platform: LINUX

system:
  projectRoot: ./
  sourceRoot: ./app
  exclude: ["*node_modules*", "*webpack*", "*app/assets*", "*app/blocks*", "*app/reducers*", "*app/utils*"]
  plugins:
    sauce:
      username: proccess.env.SAUCE_USERNAME
      accessKey: proccess.env.SAUCE_ACCESS_KEY

sets:
  local:
    files:
    - './app/tests/gemini/**/*.gemini.js'
    browsers:
    - chrome-latest
  sauce:
    files:
    - './app/tests/gemini/**/*.gemini.js'
    browsers:
    - firefox-latest

