rootUrl: http://localhost:8080/main
calibrate: false
screenshotsDir: './app/tests/gemini/screens'

browsers:
  chrome-latest:
    screenshotsDir: './app/tests/gemini/screens/chrome-screens'
    desiredCapabilities:
      browserName: chrome
      platform: LINUX
  firefox-latest:
    screenshotsDir: './app/tests/gemini/screens/ff-screens'
    calibrate: true
    desiredCapabilities:
      version: "47.0"
      browserName: firefox
      platform: WINDOWS

system:
  projectRoot: ./
  sourceRoot: ./app
  parallelLimit: 1
  exclude: ["*node_modules*", "*webpack*", "*app/assets*", "*app/blocks*", "*app/reducers*", "*app/utils*"]

sets:
  local:
    files:
    - ./app/tests/gemini/**/*.js
    browsers:
    - chrome-latest
  sauce:
    files:
    - ./app/tests/gemini/**/*.js
    browsers:
    - firefox-latest

