rootUrl: http://localhost:8080/main
calibrate: false
screenshotsDir: ./app/tests/gemini/screens

browsers:
  chrome-latest:
    desiredCapabilities:
      browserName: chrome

system:
  projectRoot: ./
  sourceRoot: ./app
  exclude: ["*node_modules*", "*webpack*", "*app/assets*", "*app/blocks*", "*app/reducers*", "*app/utils*"]

sets:
  chrome:
    files:
    - ./app/tests/gemini
    browsers:
    - chrome-latest